// Source: "Tax bill explainer version 10 corrected by Louise (1).xlsx"
//   - Tax  Inv 2026 / Tax Invoice 2025 — 31 municipal service lines each
//   - Tax rates sheet — year-specific municipal and education shares
//
// Formula (matches spreadsheet column C at C38 = resident tax):
//   educationAmount = userTax × educationShare[year]
//   userMunicipal   = userTax × municipalShare[year]
//   amount(row)     = userMunicipal × (B[row] / B$36)
//
// section: "Mississauga" | "Peel" | "Other" | "Education"

window.TAX_DATA = {
  defaultTax: 7000,
  defaultYear: 2026,
  years: {
    2025: {
      basisTotal: 1734959866.0,
      municipalShare: 0.8520114831351125,
      educationShare: 0.14798851686488745,
      items: [
        { name: "Mississauga Fire & Emergency Services", budget: 196204694.15, section: "Mississauga" },
        { name: "Mississauga Transit", budget: 126233024.67, section: "Mississauga" },
        { name: "Mississauga Roads and  winter maintenance", budget: 105588527.82, section: "Mississauga" },
        { name: "Mississauga General Government", budget: 74825407.37, section: "Mississauga", note: 1, info: "Salaries and other overhead for back office services like Finance, Human Resources, Internal Audit, and Communications." },
        { name: "Mississauga Parks, Forestry & Environment", budget: 51787574.88, section: "Mississauga" },
        { name: "Mississauga Information Technology", budget: 47448255.68, section: "Mississauga" },
        { name: "Mississauga Recreation & Culture", budget: 39532743.01, section: "Mississauga", note: 14, info: "Community centres, golf courses, sports fields, sports arenas, swimming pools, and support for arts and culture." },
        { name: "Mississauga Library", budget: 35041270.46, section: "Mississauga" },
        { name: "Mississauga Facilities & Property Management", budget: 27684832.89, section: "Mississauga", note: 2, info: "Planning and design of new facilities and maintenance of existing City facilities." },
        { name: "Mississauga Planning & Building", budget: 19566449.08, section: "Mississauga", note: 3, info: "Processing development applications from developers and residents — rezoning, site plan approval, and building permits." },
        { name: "Mississauga Regulatory Services", budget: 17073021.3, section: "Mississauga", note: 15, info: "By-law enforcement." },
        { name: "Mississauga Mayor & Members of Council", budget: 6534337.69, section: "Mississauga" },
        { name: "Peel Regional Police", budget: 472341229.0, section: "Peel" },
        { name: "Peel Housing Support", budget: 126500568.87, section: "Peel", note: 4, info: "Region of Peel’s funding for subsidized housing initiatives." },
        { name: "Peel Waste Management", budget: 77190501.0, section: "Peel" },
        { name: "Peel Paramedic Services", budget: 64707246.62, section: "Peel" },
        { name: "Peel Roads", budget: 60438532.13, section: "Peel" },
        { name: "Peel Seniors Services", budget: 32764331.95, section: "Peel", note: 5, info: "Long-term care and adult day programs for a growing population." },
        { name: "Peel Public Health", budget: 24755657.86, section: "Peel" },
        { name: "Conservation Authorities", budget: 20090954.43, section: "Other", note: 11, info: "Mississauga’s share of funding for Credit Valley Conservation, Toronto and Region Conservation Authority, and Halton Conservation Authority." },
        { name: "Peel TransHelp", budget: 18853921.95, section: "Peel" },
        { name: "Peel Business Services", budget: 17919019.8, section: "Peel", note: 7, info: "Salaries and other overhead for services like climate change, communications, finance, HR, internal audit, and procurement." },
        { name: "Peel Income Support", budget: 17422935.72, section: "Peel", note: 6, info: "Back-office costs to deliver income support programs (Ontario Works, subsidized child care). Provincial dollars don’t cover these; municipalities do." },
        { name: "Municipal Property Assessment Corporation", budget: 11802317.32, section: "Other", note: 12, info: "Decides the value of your home, on which property taxes are calculated." },
        { name: "Peel Early Years and Child Care", budget: 11740552.28, section: "Peel" },
        { name: "Peel Community Investment", budget: 10852174.78, section: "Peel", note: 8, info: "Grants to non-profits that provide services and support to vulnerable residents." },
        { name: "Peel Information and Technology", budget: 10034220.97, section: "Peel" },
        { name: "Peel Real Property Asset Management", budget: 3428248.19, section: "Peel", note: 9, info: "Operations and maintenance of Peel facilities and planning and leasing of new facilities." },
        { name: "Peel Heritage, Arts and Culture", budget: 3388418.4, section: "Peel" },
        { name: "Peel Development Services", budget: 2186597.77, section: "Peel", note: 10, info: "Input into City of Mississauga development applications to ensure infrastructure keeps up with growth." },
        { name: "Peel Regional Chair and Council", budget: 1022297.95, section: "Peel" },
      ],
    },
    2026: {
      basisTotal: 1863784101.0,
      municipalShare: 0.859362202994574,
      educationShare: 0.14063779700542603,
      items: [
        { name: "Mississauga Fire & Emergency Services", budget: 204132854.34, section: "Mississauga" },
        { name: "Mississauga Transit", budget: 145502703.67, section: "Mississauga" },
        { name: "Mississauga Roads and  winter maintenance", budget: 123582427.15, section: "Mississauga" },
        { name: "Mississauga General Government", budget: 73532358.29, section: "Mississauga", note: 1, info: "Salaries and other overhead for back office services like Finance, Human Resources, Internal Audit, and Communications." },
        { name: "Mississauga Parks, Forestry & Environment", budget: 50277707.82, section: "Mississauga" },
        { name: "Mississauga Information Technology", budget: 45976964.76, section: "Mississauga" },
        { name: "Mississauga Recreation & Culture", budget: 37937222.01, section: "Mississauga", note: 14, info: "Community centres, golf courses, sports fields, sports arenas, swimming pools, and support for arts and culture." },
        { name: "Mississauga Library", budget: 35882335.68, section: "Mississauga" },
        { name: "Mississauga Facilities & Property Management", budget: 27533243.2, section: "Mississauga", note: 2, info: "Planning and design of new facilities and maintenance of existing City facilities." },
        { name: "Mississauga Planning & Building", budget: 20484089.67, section: "Mississauga", note: 3, info: "Processing development applications from developers and residents — rezoning, site plan approval, and building permits." },
        { name: "Mississauga Regulatory Services", budget: 18507378.37, section: "Mississauga", note: 15, info: "By-law enforcement." },
        { name: "Mississauga Mayor & Members of Council", budget: 6383549.04, section: "Mississauga" },
        { name: "Peel Regional Police", budget: 519499309.0, section: "Peel" },
        { name: "Peel Housing Support", budget: 142005725.53, section: "Peel", note: 4, info: "Region of Peel’s funding for subsidized housing initiatives." },
        { name: "Peel Waste Management", budget: 83180785.75, section: "Peel" },
        { name: "Peel Paramedic Services", budget: 74148811.97, section: "Peel" },
        { name: "Peel Roads", budget: 61589805.41, section: "Peel" },
        { name: "Peel Seniors Services", budget: 36284843.06, section: "Peel", note: 5, info: "Long-term care and adult day programs for a growing population." },
        { name: "Peel Public Health", budget: 26847056.9, section: "Peel" },
        { name: "Conservation Authorities", budget: 21018055.91, section: "Other", note: 11, info: "Mississauga’s share of funding for Credit Valley Conservation, Toronto and Region Conservation Authority, and Halton Conservation Authority." },
        { name: "Peel TransHelp", budget: 20657129.2, section: "Peel" },
        { name: "Peel Income Support", budget: 19936353.34, section: "Peel", note: 6, info: "Back-office costs to deliver income support programs (Ontario Works, subsidized child care). Provincial dollars don’t cover these; municipalities do." },
        { name: "Peel Business Services", budget: 12717116.14, section: "Peel", note: 7, info: "Salaries and other overhead for services like climate change, communications, finance, HR, internal audit, and procurement." },
        { name: "Municipal Property Assessment Corporation", budget: 12203519.61, section: "Other", note: 12, info: "Decides the value of your home, on which property taxes are calculated." },
        { name: "Peel Early Years and Child Care", budget: 11698332.91, section: "Peel" },
        { name: "Peel Community Investment", budget: 10981164.32, section: "Peel", note: 8, info: "Grants to non-profits that provide services and support to vulnerable residents." },
        { name: "Peel Information and Technology", budget: 10851328.2, section: "Peel" },
        { name: "Peel Heritage, Arts and Culture", budget: 3504889.62, section: "Peel" },
        { name: "Peel Real Property Asset Management", budget: 3393559.05, section: "Peel", note: 9, info: "Operations and maintenance of Peel facilities and planning and leasing of new facilities." },
        { name: "Peel Development Services", budget: 2482851.78, section: "Peel", note: 10, info: "Input into City of Mississauga development applications to ensure infrastructure keeps up with growth." },
        { name: "Peel Regional Chair and Council", budget: 1050629.31, section: "Peel" },
      ],
    },
  },
  notes: [
    { mark: 1, text: "Salaries and other overhead for back office services like Finance, Human Resources, Internal Audit, and Communications." },
    { mark: 2, text: "Planning and design of new facilities and maintenance of existing facilities." },
    { mark: 3, text: "Processing development applications from developers and residents including rezoning, site plan approval, and building permits." },
    { mark: 4, text: "Subsidized housing." },
    { mark: 5, text: "Long-term care and adult day programs." },
    { mark: 6, text: "Back-office costs to deliver income support programs (Ontario Works, subsidized child care). These are not paid by the province and are paid by municipalities." },
    { mark: 7, text: "Salaries and other overhead for services like climate change, communications, finance, HR, internal audit, and procurement." },
    { mark: 8, text: "Grants to non-profits that provide services and support to vulnerable residents." },
    { mark: 9, text: "Operations and maintenance of Peel facilities and planning and leasing of new facilities." },
    { mark: 10, text: "Input into City of Mississauga development applications to ensure infrastructure keeps up with growth." },
    { mark: 11, text: "Mississauga’s share of funding for Credit Valley Conservation, Toronto and Region Conservation Authority, and Halton Conservation Authority." },
    { mark: 12, text: "Decides the value of your home, on which property taxes are calculated." },
    { mark: 13, text: "Education tax. The City does not receive this; it collects it on behalf of school boards." },
    { mark: 14, text: "Community centres, golf courses, sports fields, sports arenas, swimming pools, and support for arts and culture." },
    { mark: 15, text: "By-law enforcement." },
  ],
};
